return {
  ["workshop-1111658995"]={ configuration_options={  }, enabled=true },
  ["workshop-1185229307"]={
    configuration_options={
      CAMERA=true,
      DAMAGE_NUMBERS=true,
      DAMAGE_RESISTANCE=true,
      FRAME_PHASES=true,
      GLOBAL=false,
      GLOBAL_NUMBERS=false,
      HEADER_CLIENT=false,
      HEADER_SERVER=false,
      HORIZONTAL_OFFSET=0,
      TAG="EPIC",
      WETNESS_METER=false 
    },
    enabled=true 
  },
  ["workshop-1207269058"]={ configuration_options={  }, enabled=true },
  ["workshop-1530801499"]={
    configuration_options={
      ArrowsignEnable=false,
      CountdownEnable=false,
      HungerCost=2,
      Ownership=false,
      SanityCost=1 
    },
    enabled=true 
  },
  ["workshop-1595631294"]={
    configuration_options={
      BundleItems=true,
      ChangeSkin=true,
      Digornot=true,
      DragonflyChest=true,
      Icebox=true,
      SaltBox=true 
    },
    enabled=true 
  },
  ["workshop-2078243581"]={
    configuration_options={ Blue=0, Display="target", Green=0, Projectile=true, Red=1, Type="hit" },
    enabled=true 
  },
  ["workshop-2208128427"]={
    configuration_options={
      LOOT_PUMP_EQUIP=false,
      LOOT_PUMP_SCALE=1,
      LOOT_PUMP_SOUND=true,
      LOOT_PUMP_SPEED=3,
      LOOT_PUMP_TWOZN=true,
      LOOT_PUMP_WALLS=false 
    },
    enabled=true 
  },
  ["workshop-2281925291"]={
    configuration_options={ ACTIVEITEM=true, ["Client and server options"]=0, INGREDIENT=true, TINT=1 },
    enabled=true 
  },
  ["workshop-2324689937"]={
    configuration_options={
      Compatibility=false,
      config_auto_amulet=true,
      config_auto_armor=false,
      config_auto_backpack=true,
      config_auto_dress=false,
      config_mannequin=true,
      config_render=true,
      slot_amulet="extrabody3",
      slot_armor="extrabody1",
      slot_backpack=false,
      slot_costume=false,
      slot_dress="extrabody2",
      slot_heavy=false,
      ["Тype/slot mapping"]=false 
    },
    enabled=true 
  },
  ["workshop-356930882"]={
    configuration_options={ uses=10000000, uses2=10000000, uses3=10000000 },
    enabled=true 
  },
  ["workshop-362175979"]={ configuration_options={ ["Draw over FoW"]="disabled" }, enabled=true },
  ["workshop-378160973"]={
    configuration_options={
      ENABLEPINGS=true,
      FIREOPTIONS=2,
      OVERRIDEMODE=false,
      SHAREMINIMAPPROGRESS=true,
      SHOWFIREICONS=true,
      SHOWPLAYERICONS=true,
      SHOWPLAYERSOPTIONS=2 
    },
    enabled=true 
  },
  ["workshop-466732225"]={ configuration_options={  }, enabled=true },
  ["workshop-569043634"]={
    configuration_options={
      Health_Penalty_Generic="Unchanged",
      Health_Penalty_Maximum="Unchanged",
      Health_Penalty_Meat_Effigy="Unchanged",
      Health_Penalty_Portal="Unchanged",
      Health_Respawn_Amount="Unchanged",
      KeepInventory="Unchanged",
      KillMe="Unchanged",
      NoPlayerSkeletons="Unchanged",
      ReturnHotkey="Unchanged",
      ReturnHotkey_Mode="Closest",
      SpawnProtection="Unchanged",
      campfire="Enabled",
      coldfire="Enabled",
      coldfirepit="Enabled",
      firepit="Enabled",
      reviver="Unchanged",
      skeleton="Unchanged",
      usetags="Unchanged" 
    },
    enabled=true 
  },
  ["workshop-666155465"]={
    configuration_options={
      chestB=-1,
      chestG=-1,
      chestR=-1,
      display_hp=-1,
      food_estimation=-1,
      food_order=0,
      food_style=0,
      lang="auto",
      show_food_units=-1,
      show_uses=-1 
    },
    enabled=true 
  } 
}